# Generated by Django 4.2.3 on 2023-08-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('trades', models.BooleanField(help_text='Если хотите торговаться', verbose_name='торг')),
                ('date_now', models.DateTimeField(auto_now_add=True, verbose_name='Создание дата')),
                ('date_update', models.DateField(auto_now=True, verbose_name='Обновление дата')),
            ],
            options={
                'db_table': 'advertisment',
            },
        ),
    ]
